### ISSUE TITLE
Please support me

### ISSUE THREAD

**Issue by nguyenhungcn97-glitch** [Belik1982/esp32-makita-bms-reader#3]

**Comment by nguyenhungcn97-glitch** [comment]
![image](https://github.com/user-attachments/assets/052d9894-ea8e-4bfb-9189-85ecfae5fc8f)![image](https://github.com/user-attachments/assets/6c67e46e-b577-453d-8e7f-7f376ccae026)

**Comment by yukonx** [comment]
1.INSTALL "Visual Studio Code"
2.EXTENSIONS--> INSTALL "PlatformIO IDE"
3.FILE-->OPNE FOLDER  "esp32-makita-bms-reader-main"
4.PlatformIO ID-->GENERAL-->UPLOAD
5.PlatformIO ID-->Platform-->UPLOAD FILESYSTEM IMAGE

**Comment by nguyenhungcn97-glitch** [comment]
I've already done it, but now it's showing the error message in the picture. Please guide me.

**Comment by nguyenhungcn97-glitch** [comment]
![image](https://github.com/user-attachments/assets/23dc44f2-b0fa-49a9-8c29-60f6f8feb174)

**Comment by nguyenhungcn97-glitch** [comment]
When I run the program to test it, it shows this error.

**Comment by yukonx** [comment]
![Image](https://github.com/user-attachments/assets/d707da48-696c-4a75-a6fd-015c638f941f)

This is different.

**Comment by nguyenhungcn97-glitch** [comment]
![image](https://github.com/user-attachments/assets/9932773d-02a9-4770-b7ac-ae9a5a9bc459)

**Comment by nguyenhungcn97-glitch** [comment]
It still shows an error.

**Comment by nguyenhungcn97-glitch** [comment]
4.PlatformIO ID-->GENERAL-->UPLOAD
5.PlatformIO ID-->Platform-->UPLOAD FILESYSTEM IMAGE
Please support this step

**Comment by nguyenhungcn97-glitch** [comment]
![image](https://github.com/user-attachments/assets/4ef047ff-c6cc-4584-a9ab-354fd7b0ed9e)

**Comment by nguyenhungcn97-glitch** [comment]
Error. Please help me

**Comment by yukonx** [comment]
My steps

https://drive.google.com/file/d/1FqxRdMHRkPvp-KmPCuJBa5hT1eaRqxXf/view?usp=sharing

**Comment by nguyenhungcn97-glitch** [comment]
Thank i support

**Comment by nguyenhungcn97-glitch** [comment]
![image](https://github.com/user-attachments/assets/dc21f839-f726-4830-b4a4-962e5fa92e5c)

**Comment by EduCtPit** [comment]
![Image](https://github.com/user-attachments/assets/9e2a1092-4556-4318-95a5-c662ef59ba49)

Salut all..
De 2 zile ma chinui am rasfoit peste tot am tot incercat un alta..am urmat si pasii din video al lui Yukonx..nu stiu ce sa mai fac..
Va rog cum rezolv

hello everyone..
I've been struggling for 2 days, I've browsed everywhere, I've tried another one..I've also followed the steps in Yukonx's video..I don't know what else to do..
Please tell me how to solve it

**Comment by yukonx** [comment]
Sometimes switching to another computer doesn’t necessarily solve the problem.

**Comment by EduCtPit** [comment]
Ma poti ajuta? Te rog ca nu ii dau de cap.

**Comment by yukonx** [comment]
Which ESP32 development board model are you using?
Do you have the complete error message? 
Could you provide a full-screen screenshot?

**Comment by nguyenhungcn97-glitch** [comment]
![image](https://github.com/user-attachments/assets/fc11d41e-bc88-4ad2-b93e-544b7dd2c331)

**Comment by nguyenhungcn97-glitch** [comment]
Is it possible to program this ESP32 and display the output on the screen immediately? Please help

**Comment by yukonx** [comment]
> Is it possible to program this ESP32 and display the output on the screen immediately? Please help
It should be possible. You can refer to this GitHub: https://github.com/no-body-in-particular/m5din-makita/tree/main. I’m using an ESP32-S3 with a 2.4-inch ST7789 TFT to build it.

![Image](https://github.com/user-attachments/assets/b9cd187b-79f8-4898-b639-8f52ff0f8b8e)

**Comment by nguyenhungcn97-glitch** [comment]
There is no built-in circuit like the one above; it's an external display circuit.

**Comment by yukonx** [comment]
> There is no built-in circuit like the one above; it's an external display circuit.


(https://www.reddit.com/r/esp32/comments/ws6n4u/unknown_schematic_for_esp322432s028_board_anyone/?show=original)

There is a discussion thread here. If you can understand it, you might be able to get it working.

**Comment by EduCtPit** [comment]
![Image](https://github.com/user-attachments/assets/4c97660b-2048-43eb-a56d-2fa3c9550ad5)
hello again...
the board is an esp32-c3 super mini...
i switched to mac..
load Build successfully
load Upload successfully
load Build Filesystem Image successfully
load Upload Filesystem Image successfully
everything seems fine..now...but i'm looking for a network or something to see if it works and nothing..

**Comment by yukonx** [comment]
> hello again... the board is an esp32-c3 super mini... i switched to mac.. load Build successfully load Upload successfully load Build Filesystem Image successfully load Upload Filesystem Image successfully everything seems fine..now...but i'm looking for a network or something to see if it works and nothing..


In my experience, some ESP32 Super Mini development boards have antenna issues. I tried removing the antenna and replacing it with a wire, and it worked normally. You might want to give that a try.

![Image](https://github.com/user-attachments/assets/6e73b294-cd57-496d-b03c-25f70fb5f851)

**Comment by EduCtPit** [comment]
ok ..ms. I will try..
did you supply 5v separately there ..? on that red wire ?

**Comment by yukonx** [comment]
> ok ..ms. I will try.. did you supply 5v separately there ..? on that red wire ?

I used a DC-to-DC converter circuit and powered the ESP32 directly from the battery.

**Comment by EduCtPit** [comment]
I powered it separately on a USB..to see if it works...and it still doesn't work🤕
I also glued a small wire to the antenna there..
I'm holding it 2cm away from it...nothing..
What surprises me is that only that LED stays red for so long..nothing blinks.
I don't know what else to do..
any advice please..

![Image](https://github.com/user-attachments/assets/7b489fb4-2229-4042-954d-71b732f0d643)

**Comment by yukonx** [comment]
> I powered it separately on a USB..to see if it works...and it still doesn't work🤕 I also glued a small wire to the antenna there.. 

The red LED is the power indicator and stays on. I removed the entire ceramic antenna. If you have another ESP32 development board, you can flash the firmware onto it and test whether it works properly without connecting any external circuitry.

**Comment by EduCtPit** [comment]
Same...I did as you said..I loaded on the 2nd board everything was without any errors...
same result nothing appears on my wifi..🤕🤕🤕

**Comment by EduCtPit** [comment]
I also removed the ceramic..nothing..🤕🤕

![Image](https://github.com/user-attachments/assets/63a22487-7b37-4a1f-b3c3-663ce3de9fa3)

**Comment by yukonx** [comment]
I tested it again just now:
	1.	Replacing the antenna is required for it to work properly.
	2.	Replacing the antenna is not necessary.
	3.	Replacing the antenna is not necessary.

![Image](https://github.com/user-attachments/assets/48c3b511-b3f1-4b84-a71f-0ed15ef5d188)

**Comment by EduCtPit** [comment]
🤕🤕🤕it doesn't work for me....if I don't bother you too much can you give me what you upload? the files..
Maybe mine doesn't have something

**Comment by yukonx** [comment]
I just tested it again using the files provided on GitHub, and it works without any issues.

<img width="705" height="491" alt="Image" src="https://github.com/user-attachments/assets/ef9f8f97-38b8-40de-818a-d5d262be8256" />

**Comment by EduCtPit** [comment]
Gata....dupa zeci de incercari functioneaza in sfarsit..mersi de sfaturi..a 3 a zii cu noroc..

**Comment by yukonx** [comment]
> Gata....dupa zeci de incercari functioneaza in sfarsit..mersi de sfaturi..a 3 a zii cu noroc..

What changes did you end up making to get it working?

**Comment by EduCtPit** [comment]
hello..honestly, after several attempts, I don't even know what the hell I did to them..I loaded both esp32c3superMini boards..
on the second one, I think I held the Boot button down until I did the whole procedure..
Anyway, one works with the ceramic, the other without..I tried it in another room and both work..
on one, I only connected R 4.7k to the GPIO3 and GPIO4 pins...
BOTH WORK..

![Image](https://github.com/user-attachments/assets/f65a01c3-d25b-4535-8171-6a1debbb2b16)

**Comment by spfalex** [comment]
![Image](https://github.com/user-attachments/assets/581168f8-a3d4-4737-a5e2-3438a7cb1f61)
![Image](https://github.com/user-attachments/assets/2eabdb2c-60aa-4ba0-b704-c247868d6000)
![Image](https://github.com/user-attachments/assets/2256ec54-4eea-456e-92fc-ffce014988c0)
![Image](https://github.com/user-attachments/assets/3dedeccf-9099-48e8-94ad-f6cd703e1573)
![Image](https://github.com/user-attachments/assets/9637e43a-a2db-443d-8d8c-be21beb6d4fa)

I have a similar problem with the esp 32 s3 super mini board.

I made changes to the config 
board = esp 32-s3-devkit-1
After that, I got a strange error stating that it is impossible to fill in the firmware because there is not enough memory ...
This problem was solved by configuring the partition table.
board_build.partition = huge_app.csv

After that, the firmware was flooded, but the Open Makita-ESP network did not appear, I replaced the ceramic antenna with a wire, but there is no result.
Help please.

**Comment by yukonx** [comment]
1. I have an ESP32-S3 Mini development board with exactly the same issue as yours. I went to https://docs.platformio.org/en/latest/boards/index.html, found a similar board, and changed the board setting in platformio.ini. After that, everything worked fine. You can try this as well.

2.I did not add the line board_build.partition = huge_app.csv.

**Comment by tkachvlad2011-jpg** [comment]
You were right, board = adafruit_feather_esp32s3 flashed my esp32s3, but I still can't see any Wi-Fi networks. I went and bought an esp32 c3 super mini, flashed it, but I still can't see Wi-Fi networks. Any ideas what I might be doing wrong?

![Image](https://github.com/user-attachments/assets/288f15c4-49b3-43c3-a1e6-475dcb8829ea)

**Comment by tkachvlad2011-jpg** [comment]
> > Gata....dupa zeci de incercari functioneaza in sfarsit..mersi de sfaturi..a 3 a zii cu noroc..
> 
> What changes did you end up making to get it working?

I have a similar problem with these super minis, the LED is blinking, but there is no Wi-Fi network.

**Comment by yukonx** [comment]
> I have a similar problem with these super minis, the LED is blinking, but there is no Wi-Fi network.

Try this configuration. Wi-Fi works properly for me with this one, but it doesn’t work correctly with the one you’re using.

[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini

**Comment by spfalex** [comment]
> > I have a similar problem with these super minis, the LED is blinking, but there is no Wi-Fi network.
> 
> Try this configuration. Wi-Fi works properly for me with this one, but it doesn’t work correctly with the one you’re using.
> 
> [env:lolin_s3_mini] platform = espressif32 board = lolin_s3_mini

It didn't help, I don't know what to do anymore, the esp32 wroom will arrive in a few days, I'll try to make it, I recorded a video, please watch it, maybe I'm doing something wrong?

https://drive.google.com/file/d/1EnV24QQfNTwYYNXQqfkS0NSWYf4psHMo/view?usp=drivesdk

**Comment by yukonx** [comment]
> https://drive.google.com/file/d/1EnV24QQfNTwYYNXQqfkS0NSWYf4psHMo/view?usp=drivesdk

![Image](https://github.com/user-attachments/assets/95c9def7-2be4-4092-9b03-180d3970409b)

**Comment by spfalex** [comment]
Привет! С одной платой получилось, вторая работает некорректно.
Что делал.
Прошил по таоей рекомендации обе платы s3 super mini и с3 super mini вайфай так и не появился. Но у меня был собран макет и на нем же висела адуино нано, в момент прошивки я заметил что на ардуинке мигали леды. Я взял голую плату, s3 и с3 прошил, и ничего, но когда я ее трогал руками на мгновение появилась сеть. По итогу китайцы не смыли флюс, обе платы отмыл, c3 запустилась хорошо но только пришлось вместо керамической антены использовать провод, вторая s3 запустилась с родной антеной, но к сети подключается и без подключения к акб пишет что акб подключен, читает все нулями как с подключеным акб так и без него, есть мысли как заставить работать s3 super mini? На фото скрины как ведет себя эта плата.

<img width="585" height="1266" alt="Image" src="https://github.com/user-attachments/assets/4e81f12f-610a-4c07-9799-50f246417ba5" />
<img width="585" height="1266" alt="Image" src="https://github.com/user-attachments/assets/780a7518-e744-4df5-94a9-6b55515d0853" />

**Comment by yukonx** [comment]
![Image](https://github.com/user-attachments/assets/01a0248f-a00d-43e8-b107-6cf03b2c869c)

**Comment by spfalex** [comment]
> ![Image](https://github.com/user-attachments/assets/01a0248f-a00d-43e8-b107-6cf03b2c869c)
 К сожалению не помогло, я не исключаю что эта плата изначально была косячная, куплю такую же и проверю.
Можно название и фото платы которая по вашему мнению самая стабильная и не глючная?

**Comment by yukonx** [comment]
If the web interface works properly, then there shouldn’t be an issue. You can take photos of your circuit setup and share them so we can help check it.

**Comment by EduCtPit** [comment]
Proiect aproape terminat... mai astept DC-DC 5V Multumesc Yukon de ajutor..spor in toate.🙏🙏

![Image](https://github.com/user-attachments/assets/dc857bd2-cec2-4bc1-8804-0b749952254f)

![Image](https://github.com/user-attachments/assets/32fd5fea-5847-4ef3-abf6-916a55a515f7)

![Image](https://github.com/user-attachments/assets/6a5b6b30-3773-4f32-9456-8c772aa8ce4e)

![Image](https://github.com/user-attachments/assets/5cf2290e-04d1-4c64-9032-f46dcdfa33f5)

![Image](https://github.com/user-attachments/assets/78cb1cda-8bb9-4be1-ac7d-88c2e3ca2476)

**Comment by jmlcatarino** [comment]
Hi there, I have followed the video procedures for the upload  to the ESP32 but all I get is a blank screen. Can someone point me the direction on how to solve this?

**Comment by yukonx** [comment]
> Hi there, I have followed the video 


Recording a video of your process will make it easier for others to understand where the issue is occurring.

**Comment by jmlcatarino** [comment]
I did everything like in the video and all I get is a Blank page. No Captive Portal too. I'm sorry I'm not being able to record the screen on video.

**Comment by jmlcatarino** [comment]
Success! After much reading to try to understand why I wasn´t being able to upload correctly the sketch, I did it! Instead of Build like in the video, I did what @yukonx suggested earlier, from point 3 to 5, and it worked pretty well. Immediately. :) 
Thank you. Now I need to build the hardware to test it. I already have a battery to test it. 

> 1.INSTALL "Visual Studio Code" 
2.EXTENSIONS--> INSTALL "PlatformIO IDE" 
3.FILE-->OPNE FOLDER "esp32-makita-bms-reader-main" 
4.PlatformIO ID-->GENERAL-->UPLOAD 
5.PlatformIO ID-->Platform-->UPLOAD FILESYSTEM IMAGE

**Comment by voodyamc-crypto** [comment]
board = esp32-c6-devkitm-1
Нет поддержки framework = arduino
Поддерживает только = espidf
Как загрузить проект?

**Comment by yukonx** [comment]
> board = esp32-c6-devkitm-1 Нет 

You can modify the platformio.ini configuration by referring to the official documentation:
https://docs.platformio.org/en/latest/boards/espressif32/esp32-c6-devkitm-1.html
